// Generated by CoffeeScript 1.9.3
(function() {
  var LocalStorage;

  LocalStorage = (function() {
    function LocalStorage() {
      if (localStorage.getItem("created_at") === null) {
        localStorage.setItem("created_at", new Date());
      }
    }

    return LocalStorage;

  })();

}).call(this);
