// Generated by CoffeeScript 1.9.3
(function() {
  $(function() {
    var startUp, words;
    $("#question, #answer").hide();
    words = $.getJSON("spellings.json");
    $.when(words).done((function(d) {
      return startUp(d);
    }));
    $.when(words).fail(function(data, status, error) {
      console.log(status + error);
    });
    return startUp = function(data) {
      return $("#question").show();
    };
  });

}).call(this);
